"""Initial schema

Revision ID: 57fc4fb30298
Revises: 
Create Date: 2026-08-03 12:15:17.482472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fc4fb30298'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nama_divisi', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('akun_anggaran',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kode_akun', sa.String(length=50), nullable=False),
    sa.Column('nama_akun', sa.String(length=255), nullable=False),
    sa.Column('divisi_id', sa.Uuid(), nullable=False),
    sa.Column('total_pagu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['divisi_id'], ['divisi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akun_anggaran_kode_akun'), 'akun_anggaran', ['kode_akun'], unique=True)
    op.create_table('realisasi_anggaran',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('nomor_dokumen', sa.String(length=100), nullable=False),
    sa.Column('akun_anggaran_id', sa.Uuid(), nullable=False),
    sa.Column('uraian_kegiatan', sa.Text(), nullable=False),
    sa.Column('jumlah_realisasi', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bukti_transaksi_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'MENUNGGU_VERIFIKASI', 'DIVERIFIKASI', 'DITOLAK', name='statusrealisasi'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['akun_anggaran_id'], ['akun_anggaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realisasi_anggaran_nomor_dokumen'), 'realisasi_anggaran', ['nomor_dokumen'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_realisasi_anggaran_nomor_dokumen'), table_name='realisasi_anggaran')
    op.drop_table('realisasi_anggaran')
    op.drop_index(op.f('ix_akun_anggaran_kode_akun'), table_name='akun_anggaran')
    op.drop_table('akun_anggaran')
    op.drop_table('divisi')
    # ### end Alembic commands ###
